name: Run Jest Tests

on:
  push:
    branches:
      - master  # 改为 master 分支
  pull_request:
    branches:
      - master  # 改为 master 分支

jobs:
  test:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 设置 Node.js 版本

    - name: Install dependencies
      run: |
        npm install  # 安装 npm 依赖
      working-directory: ./XX1  # 设置正确的工作目录

    - name: Run tests
      run: |
        npm test  # 运行 Jest 测试
      working-directory: ./XX1  # 设置正确的工作目录
